//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.11 at 10:54:58 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cherrypie.com/spring-boot-soap-example", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cherrypie.spring_boot_soap_example;
